// TODO: FIX SIDEBAR SO ALL CONSISTENT USING ONE SIDEBAR DIV
// TODO: SORT PADDING/MARGINS ON CARDS SO ABLE TO DISPLAY 6 IN ONE ROW
// TODO: RANDOMLY DISPLAY DIFFERENT ARTIST AND ALBUMS ON PAGE LOAD
// TODO: CHANGE SEARCH BAR TO USING URLSEARCHPARAMS METHOD / UPDATE SONGS PAGE COVER
// TODO: UPDATE TAB TITLE BASED ON CURRENT PAGE / ACTIVITY
// TODO: ADD LINK ON SEE MORE BUTTONS - HOME AND ARTIST PAGE
// TODO: UPDATE ALBUM/ARTIST PAGE TO SHOW MORE POEPULAR ALBUMS UNDERNEATH